import type { BidItem } from "../types"

export const bidBoardItems: BidItem[] = [
  {
    id: "bb1",
    title: "Software Dev Project: Vague Scope",
    category: "Software Development",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Full Stack", "React", "Node.js"],
    timeRemaining: "03h 45m",
    status: "open",
    locked: false,
    fitScore: 82,
    location: "Remote",
  },
  {
    id: "bb2",
    title: "Market Research for Tech Sector",
    category: "Market Research",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Data Analysis", "Market Research", "Reports"],
    timeRemaining: "03h 45m",
    status: "open",
    locked: true,
    fitScore: 76,
    location: "US-based",
  },
  {
    id: "bb3",
    title: "Market Research for Tech Sector",
    category: "Market Research",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Competitive Analysis", "Strategy"],
    timeRemaining: "03h 45m",
    status: "open",
    locked: true,
    fitScore: 71,
  },
  {
    id: "bb4",
    title: "CRM Cleanup + Workflow Setup",
    category: "CRM Setup",
    budgetMin: 2000,
    budgetMax: 4500,
    skills: ["Salesforce", "HubSpot", "Automation"],
    timeRemaining: "05h 20m",
    status: "open",
    fitScore: 91,
    location: "Remote",
  },
  {
    id: "bb5",
    title: "Real Estate Lead Routing Support",
    category: "Real Estate Ops",
    budgetMin: 1800,
    budgetMax: 3500,
    skills: ["Lead Management", "CRM", "Real Estate"],
    timeRemaining: "02h 10m",
    status: "open",
    fitScore: 87,
  },
  {
    id: "bb6",
    title: "Contractor Scheduling Coordination",
    category: "Contractor Coordination",
    budgetMin: 1200,
    budgetMax: 2500,
    skills: ["Scheduling", "Project Mgmt", "Communication"],
    timeRemaining: "04h 00m",
    status: "open",
    locked: true,
    fitScore: 65,
  },
  {
    id: "bb7",
    title: "Market Research for Tech Sector",
    category: "Market Research",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Data Analysis", "Tech Industry", "Reports"],
    timeRemaining: "03h 45m",
    status: "open",
    locked: true,
    fitScore: 73,
  },
  {
    id: "bb8",
    title: "Market Research for Tech Sector",
    category: "Market Research",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Competitive Intel", "SaaS"],
    timeRemaining: "03h 45m",
    status: "open",
    fitScore: 79,
  },
  {
    id: "bb9",
    title: "Market Research for Tech Sector",
    category: "Market Research",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Industry Analysis", "Forecasting"],
    timeRemaining: "03h 45m",
    status: "open",
    locked: true,
    fitScore: 68,
  },
  {
    id: "bb10",
    title: "Software Dev Project: Vague Scope",
    category: "Software Development",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Backend", "Python", "APIs"],
    timeRemaining: "06h 15m",
    status: "open",
    fitScore: 85,
  },
  {
    id: "bb11",
    title: "Software Dev Project: Vague Scope",
    category: "Software Development",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["Mobile", "React Native"],
    timeRemaining: "01h 30m",
    status: "closing-soon",
    fitScore: 72,
  },
  {
    id: "bb12",
    title: "Software Dev Project",
    category: "Software Development",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["DevOps", "AWS", "CI/CD"],
    timeRemaining: "08h 00m",
    status: "open",
    locked: true,
    fitScore: 80,
  },
]

export const pendingBids: BidItem[] = [
  {
    id: "pb1",
    title: "CRM Cleanup + Workflow Setup",
    category: "CRM Setup",
    budgetMin: 2500,
    budgetMax: 5000,
    skills: ["Salesforce", "Automation"],
    timeRemaining: "Decision in 2d",
    status: "pending",
    fitScore: 91,
    submittedAmount: 3800,
    submittedDate: "Apr 12, 2026",
  },
  {
    id: "pb2",
    title: "Email Operations Overhaul",
    category: "Email Operations",
    budgetMin: 3000,
    budgetMax: 6000,
    skills: ["Email Marketing", "Deliverability"],
    timeRemaining: "Decision in 1d",
    status: "pending",
    fitScore: 77,
    submittedAmount: 4500,
    submittedDate: "Apr 13, 2026",
  },
  {
    id: "pb3",
    title: "Appointment Setting Campaign",
    category: "Appointment Setting",
    budgetMin: 1000,
    budgetMax: 2000,
    skills: ["Cold Calling", "Lead Qualification"],
    timeRemaining: "Decision in 3d",
    status: "pending",
    fitScore: 83,
    submittedAmount: 1500,
    submittedDate: "Apr 11, 2026",
  },
]

export const closingSoonBids: BidItem[] = [
  {
    id: "cs1",
    title: "Voice Support Integration",
    category: "Voice Support",
    budgetMin: 2000,
    budgetMax: 4000,
    skills: ["VoIP", "IVR", "Support Ops"],
    timeRemaining: "43m remaining",
    status: "closing-soon",
    fitScore: 88,
    recommendedAction: "Submit bid now — strong fit",
  },
  {
    id: "cs2",
    title: "Branding Package: Tech Startup",
    category: "Branding",
    budgetMin: 3500,
    budgetMax: 7000,
    skills: ["Brand Strategy", "Visual Identity"],
    timeRemaining: "28m remaining",
    status: "closing-soon",
    fitScore: 74,
    recommendedAction: "Review scope before bidding",
  },
  {
    id: "cs3",
    title: "Website Support Retainer",
    category: "Website Support",
    budgetMin: 1500,
    budgetMax: 3000,
    skills: ["WordPress", "Maintenance", "SEO"],
    timeRemaining: "52m remaining",
    status: "closing-soon",
    fitScore: 81,
    recommendedAction: "Submit bid — matches your profile",
  },
]

export const previousBids: BidItem[] = [
  {
    id: "prev1",
    title: "Lead Qualification System",
    category: "Lead Qualification",
    budgetMin: 2000,
    budgetMax: 4000,
    skills: ["Sales Ops", "CRM", "Automation"],
    timeRemaining: "",
    status: "won",
    fitScore: 92,
    submittedAmount: 3200,
    decisionDate: "Apr 8, 2026",
    projectValue: 3200,
  },
  {
    id: "prev2",
    title: "Multi-channel Support Setup",
    category: "Voice Support",
    budgetMin: 5000,
    budgetMax: 10000,
    skills: ["Omnichannel", "Zendesk", "Training"],
    timeRemaining: "",
    status: "won",
    fitScore: 85,
    submittedAmount: 7500,
    decisionDate: "Apr 5, 2026",
    projectValue: 7500,
  },
  {
    id: "prev3",
    title: "Market Research: Fintech",
    category: "Market Research",
    budgetMin: 2500,
    budgetMax: 5000,
    skills: ["Fintech", "Analysis", "Reports"],
    timeRemaining: "",
    status: "lost",
    fitScore: 71,
    submittedAmount: 4000,
    decisionDate: "Apr 3, 2026",
    note: "Client selected lower-budget provider",
  },
  {
    id: "prev4",
    title: "Workflow Automation: E-commerce",
    category: "Workflow Automation",
    budgetMin: 3000,
    budgetMax: 6000,
    skills: ["Shopify", "Zapier", "Process Design"],
    timeRemaining: "",
    status: "won",
    fitScore: 89,
    submittedAmount: 4800,
    decisionDate: "Mar 29, 2026",
    projectValue: 4800,
  },
  {
    id: "prev5",
    title: "Real Estate CRM Migration",
    category: "Real Estate Ops",
    budgetMin: 4000,
    budgetMax: 8000,
    skills: ["CRM Migration", "Data", "Real Estate"],
    timeRemaining: "",
    status: "lost",
    fitScore: 66,
    submittedAmount: 6500,
    decisionDate: "Mar 25, 2026",
    note: "Scope changed after submission",
  },
]
